name: front deploy for dev

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-21.10

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install Dependencies
        run: |
          yarn
          
      - name: Build
        run: |
          yarn build