name: React tests

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-21.10

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.12.0'

      - name: Install Dependencies
        run: |
          yarn

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          node-version: '18.12.0'
          path: '**/node_modules'
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-
            
      - name: Build
        run: |
          yarn build